// Apna Fashion Mart seed data

export const AFM_DATA = {
  cities: ['Mumbai', 'Bengaluru', 'Delhi', 'Jaipur', 'Hyderabad'],
  activeCity: 'Mumbai · Bandra West',

  categories: [
    { id: 'women',  label: "Women's",    items: '12.4k',
      img: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80&auto=format&fit=crop' },
    { id: 'men',    label: "Men's",      items: '8.2k',
      img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80&auto=format&fit=crop' },
    { id: 'ethnic', label: 'Ethnic',     items: '6.7k',
      img: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80&auto=format&fit=crop' },
    { id: 'kids',   label: 'Kids',       items: '3.1k',
      img: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&q=80&auto=format&fit=crop' },
    { id: 'street', label: 'Streetwear', items: '2.8k',
      img: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80&auto=format&fit=crop' },
    { id: 'foot',   label: 'Footwear',   items: '4.5k',
      img: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&q=80&auto=format&fit=crop' },
    { id: 'acc',    label: 'Accessories', items: '5.9k',
      img: 'https://images.unsplash.com/photo-1485518882345-15568b007407?w=600&q=80&auto=format&fit=crop' },
    { id: 'lux',    label: 'Luxury',     items: '1.2k',
      img: 'https://images.unsplash.com/photo-1581338834647-b0fb40704e21?w=600&q=80&auto=format&fit=crop' },
  ],

  howItWorks: [
    { n: '01', t: 'Drop a pin', s: 'Allow location or type your neighborhood. We scan within 25 km.' },
    { n: '02', t: 'Discover boutiques', s: 'Browse verified independent storefronts curated for your city.' },
    { n: '03', t: 'Try, wishlist, order', s: 'View garments in 3D · request a try-on · order online or visit.' },
    { n: '04', t: 'Same-day arrives', s: 'Free local delivery above ₹999 from verified partner shops.' },
  ],

  testimonials: [
    { name: 'Priya Sharma', area: 'Bandra · Mumbai', rating: 5,
      quote: 'I discovered three independent labels in my own neighborhood that I had no idea existed. The 3D try-on saved me a round-trip to the store.' },
    { name: 'Aditya Rao',   area: 'Koramangala · Bengaluru', rating: 5,
      quote: 'My boutique gets more walk-ins from the app than from Google. The verification badge is the trust signal that converts.' },
    { name: 'Anisha Mehra', area: 'Hauz Khas · Delhi', rating: 4,
      quote: 'Same-day delivery, return picked up the next morning. The whole flow feels Apple-grade — but the clothes are from a 12-year-old family shop.' },
  ],

  appFeatures: [
    'Geolocation-first home',
    '3D & 360° product previews',
    'Live order tracking',
    'AI fashion assistant',
    'AR try-on (selected items)',
    'Push offers from your boutiques',
  ],

  specs: [
    { k: 'Fabric',         v: '100% mulberry silk · handloom-woven' },
    { k: 'Weave',          v: 'Banarasi katan brocade' },
    { k: 'Length',         v: '6.3 m saree + 0.8 m blouse piece' },
    { k: 'Weight',         v: '720 g' },
    { k: 'Care',           v: 'Dry-clean only · do not bleach · iron on low' },
    { k: 'Origin',         v: 'Varanasi, Uttar Pradesh' },
    { k: 'Pattern',        v: 'Floral jaal with zari border' },
    { k: 'Style',          v: 'Bridal · Festive · Heirloom' },
    { k: 'Pallu',          v: 'Hand-finished with 32 g real zari thread' },
    { k: 'Blouse',         v: 'Unstitched piece included · tailor-ready' },
    { k: 'Made by',        v: 'Aanya Atelier · Bandra West' },
    { k: 'SKU',            v: 'AFM-AA-SS-04217' },
  ],

  inBox: [
    'Handloom silk saree (6.3 m)',
    'Unstitched matching blouse piece (0.8 m)',
    'Cotton fall pre-stitched',
    'Authenticity certificate · weaver-signed',
    'AFM Verified-Boutique tag',
    'Reusable cloth pouch packaging',
  ],

  sizeChart: [
    { label: 'XS', bust: '32', waist: '26', hip: '36', length: 'free' },
    { label: 'S',  bust: '34', waist: '28', hip: '38', length: 'free' },
    { label: 'M',  bust: '36', waist: '30', hip: '40', length: 'free' },
    { label: 'L',  bust: '38', waist: '32', hip: '42', length: 'free' },
    { label: 'XL', bust: '40', waist: '34', hip: '44', length: 'free' },
  ],

  reviews: [
    { name: 'Priya Sharma',  verified: true,  rating: 5, when: '2 weeks ago · Mumbai',
      title: 'Heirloom-grade. Absolutely worth it.',
      body: 'I bought this for my sister\'s sangeet. The zari is real — it catches light like nothing on Myntra or Ajio I\'ve seen. Aanya\'s team called to confirm my measurements personally.',
      photos: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=200&q=80&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1610189019687-b96d5d44b96f?w=200&q=80&auto=format&fit=crop',
      ] },
    { name: 'Ananya Iyer',   verified: true,  rating: 5, when: '1 month ago · Bengaluru',
      title: 'The 3D viewer is the reason I bought.',
      body: 'I was nervous ordering a 5K saree online. The 360° viewer + AR try-on basically removed all doubt. Delivery was 26 hours from Bandra to Koramangala.',
      photos: [] },
    { name: 'Mira S.',       verified: false, rating: 4, when: '6 days ago · Delhi',
      title: 'Beautiful · slight color difference from screen',
      body: 'The maroon is a shade deeper in person — more bridal, less rosewood. Still gorgeous, just adjust expectations. Stitching is impeccable.',
      photos: [
        'https://images.unsplash.com/photo-1623013438264-d2a8b4f1cb16?w=200&q=80&auto=format&fit=crop',
      ] },
    { name: 'Rhea K.',       verified: true,  rating: 5, when: '3 weeks ago · Jaipur',
      title: 'Tailor approved · pallu fall is perfect',
      body: 'My tailor said this is the kind of weaving you only get from third-gen Varanasi karkhanas. He charged me less because the fabric was that clean.',
      photos: [] },
  ],

  ratingBreakdown: [
    { stars: 5, count: 168, pct: 77 },
    { stars: 4, count: 32,  pct: 15 },
    { stars: 3, count: 11,  pct: 5 },
    { stars: 2, count: 4,   pct: 2 },
    { stars: 1, count: 3,   pct: 1 },
  ],

  filters: ['Verified only', 'Open now', 'Free delivery', 'Within 5 km'],
  radii: ['1 km', '3 km', '5 km', '10 km', '25 km'],

  boutiques: [
    {
      id: 'aanya',
      name: 'Aanya Atelier',
      area: 'Bandra West, Mumbai',
      tags: ['Ethnic', 'Bridal', 'Handloom'],
      rating: 4.8,
      reviews: 412,
      distance: '1.4 km',
      open: true,
      hours: 'Closes 9 pm',
      verified: true,
      img: 'https://images.unsplash.com/photo-1693987644236-3c440256784b?w=800&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #11375E 0%, #001F3F 65%, #001428 100%)',
      x: 36, y: 42,
      initial: 'Aa',
    },
    {
      id: 'mira',
      name: 'Mira Weaves',
      area: 'Khar West, Mumbai',
      tags: ['Sarees', 'Banarasi', 'Silk'],
      rating: 4.6,
      reviews: 287,
      distance: '2.1 km',
      open: true,
      hours: 'Closes 10 pm',
      verified: true,
      img: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FF55B0 0%, #CC1377 60%, #6D1B5C 100%)',
      x: 62, y: 28,
      initial: 'Mw',
    },
    {
      id: 'kala',
      name: 'Kala Streetwear',
      area: 'Lokhandwala, Mumbai',
      tags: ['Streetwear', "Men's", 'Sneakers'],
      rating: 4.4,
      reviews: 198,
      distance: '2.7 km',
      open: true,
      hours: 'Closes 11 pm',
      verified: false,
      img: 'https://images.unsplash.com/photo-1701759164397-d49e71987ab5?w=800&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #2F3A4A 0%, #1B2230 100%)',
      x: 28, y: 70,
      initial: 'Ks',
    },
    {
      id: 'rumi',
      name: 'Rumi Bazaar',
      area: 'Pali Hill, Mumbai',
      tags: ['Western', 'Casual', 'Denim'],
      rating: 4.7,
      reviews: 324,
      distance: '1.9 km',
      open: true,
      hours: 'Closes 9 pm',
      verified: true,
      img: 'https://images.unsplash.com/photo-1563099599-7d779f2b3b86?w=800&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #C9A24A 0%, #8B6E2A 100%)',
      x: 72, y: 62,
      initial: 'Rb',
    },
  ],

  products: [
    // ===== ETHNIC / SAREES =====
    { id: 'p1', category: 'ethnic', subcat: 'saree', gender: 'women', name: 'Handloom Silk Saree', store: 'Aanya Atelier',
      price: 4899, oldPrice: 6200, rating: 4.8,
      img: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7 0%, #F8F9FB 100%)',
      darkBg: 'linear-gradient(160deg, #11375E, #001F3F)',
      initial: 'Aa', badges: ['new'], is3d: true,
      colors: ['#001F3F', '#FF1493', '#C9A24A', '#0B0F18'],
      sizes: ['XS', 'S', 'M', 'L'],
      desc: 'Hand-woven silk saree finished in Varanasi. Aanya Atelier sources directly from third-generation handloom weavers.',
      distance: '1.4 km' },
    { id: 'p1b', category: 'ethnic', subcat: 'saree', gender: 'women', name: 'Maroon Tussar Saree', store: 'Aanya Atelier',
      price: 3899, oldPrice: 4900, rating: 4.7,
      img: 'https://images.unsplash.com/photo-1583391733981-8698e58491c5?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #6D1B5C, #001F3F)', initial: 'Aa', badges: ['sale'], is3d: true,
      colors: ['#6D1B5C', '#001F3F', '#C9A24A'], sizes: ['Free'], distance: '1.4 km' },
    { id: 'p1c', category: 'ethnic', subcat: 'saree', gender: 'women', name: 'Gold-zari Banarasi Saree', store: 'Mira Weaves',
      price: 6499, oldPrice: 8200, rating: 4.9,
      img: 'https://images.unsplash.com/photo-1610189019687-b96d5d44b96f?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #C9A24A, #8B6E2A)', initial: 'Mw', badges: ['sale', '3d'], is3d: true,
      colors: ['#C9A24A', '#001F3F', '#6D1B5C'], sizes: ['Free'], distance: '2.1 km' },
    { id: 'p1d', category: 'ethnic', subcat: 'saree', gender: 'women', name: 'Indigo Kanjivaram Saree', store: 'Mira Weaves',
      price: 5499, rating: 4.6,
      img: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #11375E, #001F3F)', initial: 'Mw', badges: [],
      colors: ['#11375E', '#001F3F'], sizes: ['Free'], distance: '2.1 km' },

    // ===== ETHNIC / LEHENGA =====
    { id: 'p2', category: 'ethnic', subcat: 'lehenga', gender: 'women', name: 'Banarasi Tussar Lehenga', store: 'Mira Weaves',
      price: 4839, oldPrice: 6200, rating: 4.6,
      img: 'https://images.unsplash.com/photo-1610189019687-b96d5d44b96f?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FF55B0, #CC1377)', initial: 'Mw', badges: ['sale', '3d'], is3d: true,
      colors: ['#CC1377', '#001F3F', '#C9A24A'], sizes: ['S', 'M', 'L'], distance: '2.1 km' },
    { id: 'p2b', category: 'ethnic', subcat: 'lehenga', gender: 'women', name: 'Pastel Bridal Lehenga', store: 'Aanya Atelier',
      price: 12499, oldPrice: 15800, rating: 4.9,
      img: 'https://images.unsplash.com/photo-1610189019687-b96d5d44b96f?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #F6EFDB, #FFEDF7)', initial: 'Aa', badges: ['sale', '3d'], is3d: true,
      colors: ['#F6EFDB', '#FFEDF7', '#C9A24A'], sizes: ['XS', 'S', 'M', 'L'], distance: '1.4 km' },

    // ===== ETHNIC / KURTAS =====
    { id: 'p4', category: 'ethnic', subcat: 'kurta', gender: 'women', name: 'Chikankari Anarkali Kurta', store: 'Rumi Bazaar',
      price: 2199, oldPrice: 2799, rating: 4.7,
      img: 'https://images.unsplash.com/photo-1623013438264-d2a8b4f1cb16?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #F6EFDB, #C9A24A)', initial: 'Rb', badges: ['sale'],
      colors: ['#F6EFDB', '#11375E', '#FF1493'], sizes: ['XS', 'S', 'M', 'L'], distance: '1.9 km' },
    { id: 'p4b', category: 'ethnic', subcat: 'kurta', gender: 'women', name: 'Mul-cotton Anarkali Set', store: 'Aanya Atelier',
      price: 1899, rating: 4.5,
      img: 'https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7, #FF55B0)', initial: 'Aa', badges: ['new'],
      colors: ['#FFEDF7', '#FF1493'], sizes: ['XS','S','M','L','XL'], distance: '1.4 km' },
    { id: 'p4c', category: 'ethnic', subcat: 'kurta', gender: 'women', name: 'Hand-block Kurta', store: 'Rumi Bazaar',
      price: 1499, oldPrice: 1899, rating: 4.4,
      img: 'https://images.unsplash.com/photo-1623013438264-d2a8b4f1cb16?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7, #FF55B0)', initial: 'Rb', badges: ['sale'],
      colors: ['#FF1493', '#FFEDF7'], sizes: ['S','M','L','XL'], distance: '1.9 km' },

    // ===== ETHNIC / BRIDAL =====
    { id: 'p6', category: 'ethnic', subcat: 'bridal', gender: 'women', name: 'Mulmul Cotton Set', store: 'Aanya Atelier',
      price: 2899, oldPrice: 3499, rating: 4.9,
      img: 'https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7, #FF55B0)', initial: 'Aa', badges: ['sale', '3d'], is3d: true,
      colors: ['#FF55B0', '#FFEDF7', '#001F3F'], sizes: ['S', 'M', 'L'], distance: '1.4 km' },

    // ===== STREETWEAR / MEN =====
    { id: 'p3', category: 'street', subcat: 'shirt', gender: 'men', name: 'Oversized Linen Shirt', store: 'Kala Streetwear',
      price: 1499, rating: 4.4,
      img: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #2F3A4A, #1B2230)', initial: 'Ks', badges: [],
      colors: ['#2F3A4A', '#0B0F18', '#FFFFFF'], sizes: ['S', 'M', 'L', 'XL'], distance: '2.7 km' },
    { id: 'p5', category: 'street', subcat: 'trouser', gender: 'men', name: 'Pleated Crepe Trousers', store: 'Kala Streetwear',
      price: 1899, rating: 4.3,
      img: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #0B0F18, #1B2230)', initial: 'Ks', badges: ['new'],
      colors: ['#0B0F18', '#2F3A4A'], sizes: ['S', 'M', 'L', 'XL'], distance: '2.7 km' },
    { id: 'p3b', category: 'street', subcat: 'tee', gender: 'men', name: 'Graphic Tee · Mumbai Local', store: 'Kala Streetwear',
      price: 899, oldPrice: 1299, rating: 4.5,
      img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFFFFF, #F1F3F6)', initial: 'Ks', badges: ['sale','new'],
      colors: ['#FFFFFF', '#0B0F18', '#FF1493'], sizes: ['S','M','L','XL','XXL'], distance: '2.7 km' },
    { id: 'p3c', category: 'street', subcat: 'jacket', gender: 'men', name: 'Denim Trucker Jacket', store: 'Kala Streetwear',
      price: 2799, rating: 4.6,
      img: 'https://images.unsplash.com/photo-1495121605193-b116b5b9c5fe?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #2F3A4A, #11375E)', initial: 'Ks', badges: ['new'],
      colors: ['#11375E', '#2F3A4A'], sizes: ['S','M','L','XL'], distance: '2.7 km' },
    { id: 'p3d', category: 'street', subcat: 'hoodie', gender: 'men', name: 'Pullover Hoodie · Black', store: 'Kala Streetwear',
      price: 1899, oldPrice: 2399, rating: 4.4,
      img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #0B0F18, #1B2230)', initial: 'Ks', badges: ['sale'],
      colors: ['#0B0F18', '#FFFFFF'], sizes: ['M','L','XL','XXL'], distance: '2.7 km' },

    // ===== ETHNIC / MEN =====
    { id: 'p7', category: 'ethnic', subcat: 'sherwani', gender: 'men', name: 'Embroidered Sherwani', store: 'Mira Weaves',
      price: 7299, rating: 4.5,
      img: 'https://images.unsplash.com/photo-1622445275576-721325763afe?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #C9A24A, #001F3F)', initial: 'Mw', badges: ['new'], is3d: true,
      colors: ['#C9A24A', '#001F3F', '#0B0F18'], sizes: ['M', 'L', 'XL'], distance: '2.1 km' },
    { id: 'p7b', category: 'ethnic', subcat: 'kurta-m', gender: 'men', name: 'Cotton Kurta Pyjama Set', store: 'Mira Weaves',
      price: 1899, rating: 4.4,
      img: 'https://images.unsplash.com/photo-1622445275576-721325763afe?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7, #C9A24A)', initial: 'Mw', badges: [],
      colors: ['#FFEDF7', '#001F3F'], sizes: ['M','L','XL','XXL'], distance: '2.1 km' },

    // ===== WESTERN / WOMEN =====
    { id: 'p8', category: 'women', subcat: 'kaftan', gender: 'women', name: 'Block-print Kaftan', store: 'Rumi Bazaar',
      price: 1299, rating: 4.2,
      img: 'https://images.unsplash.com/photo-1583391733981-8698e58491c5?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FF1493, #6D1B5C)', initial: 'Rb', badges: [],
      colors: ['#FF1493', '#6D1B5C'], sizes: ['S', 'M', 'L'], distance: '1.9 km' },
    { id: 'p8b', category: 'women', subcat: 'dress', gender: 'women', name: 'A-line Linen Dress', store: 'Rumi Bazaar',
      price: 2199, oldPrice: 2799, rating: 4.6,
      img: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #FFEDF7, #FFFFFF)', initial: 'Rb', badges: ['sale','new'], is3d: true,
      colors: ['#FFFFFF', '#FFEDF7', '#001F3F'], sizes: ['XS','S','M','L'], distance: '1.9 km' },
    { id: 'p8c', category: 'women', subcat: 'top', gender: 'women', name: 'Silk Bralette Top', store: 'Rumi Bazaar',
      price: 1099, rating: 4.4,
      img: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #11375E, #001F3F)', initial: 'Rb', badges: ['new'],
      colors: ['#11375E', '#0B0F18'], sizes: ['XS','S','M','L'], distance: '1.9 km' },
    { id: 'p8d', category: 'women', subcat: 'denim', gender: 'women', name: 'High-rise Mom Jeans', store: 'Rumi Bazaar',
      price: 1799, oldPrice: 2299, rating: 4.5,
      img: 'https://images.unsplash.com/photo-1495121605193-b116b5b9c5fe?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #11375E, #001F3F)', initial: 'Rb', badges: ['sale'],
      colors: ['#11375E'], sizes: ['26','28','30','32','34'], distance: '1.9 km' },
    { id: 'p8e', category: 'women', subcat: 'co-ord', gender: 'women', name: 'Linen Co-ord Set', store: 'Aanya Atelier',
      price: 2999, rating: 4.7,
      img: 'https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=700&q=80&auto=format&fit=crop',
      bg: 'linear-gradient(160deg, #F6EFDB, #FFFFFF)', initial: 'Aa', badges: ['new'], is3d: true,
      colors: ['#F6EFDB', '#FFFFFF', '#FF1493'], sizes: ['XS','S','M','L'], distance: '1.4 km' },
  ],

  trust: [
    { ico: 'shield-check', t: 'Verified Sellers', s: 'Every boutique vetted on-site' },
    { ico: 'pin', t: 'Hyperlocal', s: 'Boutiques within 5 km of you' },
    { ico: 'truck', t: 'Same-day Delivery', s: 'Free above ₹999 · verified shops' },
    { ico: 'box', t: 'Easy 7-day Returns', s: 'No-questions-asked policy' },
  ],
};
